project:
  type: website
  output-dir: docs

website:
  title: "Sharon Voon"
  back-to-top-navigation: true
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: About Me
        href: "#background"
      - blogs.qmd
    logo: imgs/favicon.png
    logo-alt: SV
    logo-href: index.qmd
    tools:
      - icon: github
        href: https://github.com/s-voon
      - icon: linkedin
        href: https://www.linkedin.com/in/sharonvoon/ 
  favicon: imgs/favicon.png
  page-footer:
    border: True
    left: "Copyright 2024, Sharon Voon"
    right:
      - icon: github
        href: https://github.com/s-voon
      - icon: linkedin
        href: https://www.linkedin.com/in/sharonvoon/ 

format:
  html:
    page-layout: full
    theme: 
      light: lux
      dark: cyborg
    toc: true
    css: styles.css



